<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_PowerControlledHeaterFan" Id="{10dcde4f-7a77-4815-919a-97a9baa05130}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PowerControlledHeaterFan EXTENDS FB_Actuator2Point

VAR
	
	//I/O Links	
	bSetStatusOn_OUT 	AT %Q*	: 	BOOL := FALSE;		
	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[SelectControlMode();]]></ST>
    </Implementation>
    <Method Name="SetState_BO" Id="{d8943a6b-21e0-4638-9af5-20b5899f0cc2}">
      <Declaration><![CDATA[METHOD SetState_BO : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[//output
bSetStatusOn_OUT := bSetStatusOn;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_PowerControlledHeaterFan">
      <LineId Id="126" Count="0" />
    </LineIds>
    <LineIds Name="FB_PowerControlledHeaterFan.SetState_BO">
      <LineId Id="6" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>