<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_HNLTSystem" Id="{ad378e4f-4dcc-4fbd-a624-889931407b46}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HNLTSystem
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	
	// heat counters
	WMZ246 : FB_MollineC3HeatCounter;
	WMZ247 : FB_MollineC3HeatCounter;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[WMZ246(aHeatCounterTelegramm := MBus.Telegramm_WMZ_246);
WMZ247(aHeatCounterTelegramm := MBus.Telegramm_WMZ_247);]]></ST>
    </Implementation>
    <LineIds Name="FB_HNLTSystem">
      <LineId Id="9" Count="0" />
      <LineId Id="15" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>